services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Password123@
      MYSQL_DATABASE: library_management_system
      MYSQL_USER: admin
      MYSQL_PASSWORD: Password123@
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: